### ISSUE TITLE
Trivia API 

### ISSUE THREAD

**Issue by malenchite** [malenchite/trivia-trainer#6]
Research into Open Trivia API and how we will use it

**Comment by chrisrisseler** [comment]
easy difficulty=easy
medium difficulty=medium
hard difficulty=hard

**Comment by chrisrisseler** [comment]
always put type=multiple

**Comment by chrisrisseler** [comment]
category=
general knowledge: 9
books: 10
film: 11
music: 12
musicals and theatre: 13
tv: 14
video games: 15
board games: 16
science and nature: 17
computers: 18
math: 19
mythology: 20
sports: 21
geography: 22
history: 23
politics: 24
art: 25
celebrities: 26
animals: 27
vehicles: 28
comics(books): 29
gadgets: 30
anime: 31
cartoons and animation: 32

**Comment by chrisrisseler** [comment]
https://opentdb.com/api.php?amount= should be the starting part of the api call.
